version: '2'
services:
    jhipstertasks-app:
        image: jhipstertasks
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstertasks-mysql:3306/jhipstertasks?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertasks-mysql:
        extends:
            file: mysql.yml
            service: jhipstertasks-mysql
